GBENCHMARK_VERSION = 1.8.3
GBENCHMARK_SITE = $(call github,google,benchmark,v$(GBENCHMARK_VERSION))
GBENCHMARK_INSTALL_STAGING = YES
GBENCHMARK_INSTALL_TARGET = NO
GBENCHMARK_LICENSE = BSD-3-Clause
GBENCHMARK_LICENSE_FILES = LICENSE
GBENCHMARK_CPE_ID_VENDOR = google
GBENCHMARK_CPE_ID_PRODUCT = google_test
GBENCHMARK_DEPENDENCIES = gtest
GBENCHMARK_CONF_OPTS = -DBENCHMARK_ENABLE_TESTING=OFF

$(eval $(cmake-package))
